import { execSync } from 'node:child_process';

import type { ExpoConfig } from 'expo/config';

/**
 * Which commit this build came from.
 *
 * EAS sets `EAS_BUILD_GIT_COMMIT_HASH`, and that is the answer that matters — a TestFlight report
 * has to name an exact commit or "version 0.1.0" stops meaning anything after the third build.
 * Locally there is no such variable, so git is asked directly; and where neither works the answer
 * is `unknown` rather than a guess, because a wrong SHA in a bug report is worse than no SHA.
 */
function gitSha(): string {
  const fromEas = process.env.EAS_BUILD_GIT_COMMIT_HASH;
  if (fromEas !== undefined && fromEas !== '') return fromEas.slice(0, 12);

  try {
    return execSync('git rev-parse --short=12 HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return 'unknown';
  }
}

/**
 * Which backend and build profile this binary belongs to.
 *
 * The failure this exists to prevent: a preview build quietly pointed at production because
 * someone copied a `.env`. Naming the environment inside the app makes that visible in the first
 * screenshot of a bug report instead of after an afternoon of confusion.
 */
const appEnv = process.env.EAS_BUILD_PROFILE ?? 'development';

/**
 * GutSignal Expo configuration.
 *
 * `bundleIdentifier` is CONFIRMED by the project owner (2026-08-24) and must not change: it
 * is the app's permanent identity on the App Store, and a different value is a different app.
 * The Android `package` matches it and carries the same permanence on Google Play.
 *
 * Permission strings live here (not in a plist) because GutSignal uses Continuous Native
 * Generation: `ios/` is generated by EAS and is never committed.
 */
const config: ExpoConfig = {
  name: 'GutSignal',
  slug: 'gutsignal',
  version: '0.1.0',
  orientation: 'portrait',
  scheme: 'gutsignal',
  userInterfaceStyle: 'automatic',
  assetBundlePatterns: ['**/*'],

  ios: {
    supportsTablet: false,
    // Required for Sign in with Apple. The matching capability must also be enabled on the
    // App ID in the Apple Developer portal before a build can use it.
    usesAppleSignIn: true,
    bundleIdentifier: 'com.vivaan.gutsignal',
    buildNumber: '1',
    infoPlist: {
      // Export compliance: GutSignal uses only standard HTTPS/OS encryption, so App Store
      // Connect stops asking on every upload. Revisit if custom cryptography is ever added.
      ITSAppUsesNonExemptEncryption: false,
    },
  },

  android: {
    package: 'com.vivaan.gutsignal',
    predictiveBackGestureEnabled: false,
  },

  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: '#17171C',
        image: './assets/images/splash-icon.png',
        imageWidth: 96,
      },
    ],
    'expo-apple-authentication',
    'expo-secure-store',
    'expo-sqlite',
    // Diary export hands a file to the iOS share sheet (spec §98). The plugin is what makes the
    // native share capability available; without it `Sharing.isAvailableAsync()` answers false on
    // a real build while everything still works in Metro.
    'expo-sharing',
  ],

  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },

  extra: {
    eas: {
      // Populated by `eas init`.
      projectId: undefined,
    },
    /**
     * Build provenance, read by the diagnostics screen (spec §108, review §23–24).
     *
     * Identifiers only. Nothing here is a secret, and nothing here may become one — this object is
     * compiled into the bundle and readable by anyone who downloads the app.
     */
    build: {
      gitSha: gitSha(),
      appEnv,
      builtAt: new Date().toISOString(),
    },
  },
};

export default config;
