import type { ExpoConfig } from 'expo/config';

/**
 * GutSignal Expo configuration.
 *
 * `bundleIdentifier` is PROVISIONAL — it must match the identifier registered in App Store
 * Connect before the first production build. Changing it after a store release is not
 * possible, so it is confirmed with the project owner at Milestone 1 sign-off.
 *
 * Permission strings live here (not in a plist) because GutSignal uses Continuous Native
 * Generation: `ios/` is generated by EAS and is never committed.
 */
const config: ExpoConfig = {
  name: 'GutSignal',
  slug: 'gutsignal',
  version: '0.1.0',
  orientation: 'portrait',
  scheme: 'gutsignal',
  userInterfaceStyle: 'automatic',
  assetBundlePatterns: ['**/*'],

  ios: {
    supportsTablet: false,
    // Required for Sign in with Apple. The matching capability must also be enabled on the
    // App ID in the Apple Developer portal before a build can use it.
    usesAppleSignIn: true,
    bundleIdentifier: 'com.gutsignal.app',
    buildNumber: '1',
    infoPlist: {
      // Export compliance: GutSignal uses only standard HTTPS/OS encryption, so App Store
      // Connect stops asking on every upload. Revisit if custom cryptography is ever added.
      ITSAppUsesNonExemptEncryption: false,
    },
  },

  android: {
    package: 'com.gutsignal.app',
    predictiveBackGestureEnabled: false,
  },

  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: '#17171C',
        image: './assets/images/splash-icon.png',
        imageWidth: 96,
      },
    ],
    'expo-apple-authentication',
    'expo-secure-store',
    'expo-sqlite',
  ],

  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },

  extra: {
    eas: {
      // Populated by `eas init`.
      projectId: undefined,
    },
  },
};

export default config;
