import type { ExpoConfig } from 'expo/config';

/**
 * GutSignal Expo configuration.
 *
 * `bundleIdentifier` is CONFIRMED by the project owner (2026-08-24) and must not change: it
 * is the app's permanent identity on the App Store, and a different value is a different app.
 * The Android `package` matches it and carries the same permanence on Google Play.
 *
 * Permission strings live here (not in a plist) because GutSignal uses Continuous Native
 * Generation: `ios/` is generated by EAS and is never committed.
 */
const config: ExpoConfig = {
  name: 'GutSignal',
  slug: 'gutsignal',
  version: '0.1.0',
  orientation: 'portrait',
  scheme: 'gutsignal',
  userInterfaceStyle: 'automatic',
  assetBundlePatterns: ['**/*'],

  ios: {
    supportsTablet: false,
    // Required for Sign in with Apple. The matching capability must also be enabled on the
    // App ID in the Apple Developer portal before a build can use it.
    usesAppleSignIn: true,
    bundleIdentifier: 'com.vivaan.gutsignal',
    buildNumber: '1',
    infoPlist: {
      // Export compliance: GutSignal uses only standard HTTPS/OS encryption, so App Store
      // Connect stops asking on every upload. Revisit if custom cryptography is ever added.
      ITSAppUsesNonExemptEncryption: false,
    },
  },

  android: {
    package: 'com.vivaan.gutsignal',
    predictiveBackGestureEnabled: false,
  },

  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: '#17171C',
        image: './assets/images/splash-icon.png',
        imageWidth: 96,
      },
    ],
    'expo-apple-authentication',
    'expo-secure-store',
    'expo-sqlite',
    // Diary export hands a file to the iOS share sheet (spec §98). The plugin is what makes the
    // native share capability available; without it `Sharing.isAvailableAsync()` answers false on
    // a real build while everything still works in Metro.
    'expo-sharing',
  ],

  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },

  extra: {
    eas: {
      // Populated by `eas init`.
      projectId: undefined,
    },
  },
};

export default config;
